version: "3"
services:
  app:
    image: golang:1.15.13-alpine3.14
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: go run main.go
    ports:
      - "8080:8080"
